In [2]:
import tensorflow as tf
import numpy as np

In [12]:
#Matrix multiplication

tensor_1 = tf.eye(2, 3, [1])
tensor_2 = tf.eye(3, 4, [2])
tensor_1.shape, tensor_2.shape

(TensorShape([1, 2, 3]), TensorShape([2, 3, 4]))

In [4]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.]]], dtype=float32)>

if tensor_1 shape is [x, y, z], tensor_2 shape should be [y, z, a]
where y and z match

In [5]:
tensor_3 = tf.ones([3, 2, 2])
tensor_3

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [6]:
# Change shape
tf.reshape(tensor_3, [4, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [46]:
tensor_4 = tf.random.Generator.from_seed(2).normal(shape=(2, 3, 4))
tensor_5 = tf.random.Generator.from_seed(2).uniform(shape=(3, 4, 10))

tf.matmul(tensor_4, tensor_5)

InvalidArgumentError: In[0] and In[1] must have compatible batch dimensions: [2,3,4] vs. [3,4,10] [Op:BatchMatMulV2]