In [3]:
import tensorflow as tf
import numpy as np

In [12]:
#Matrix multiplication

tensor_1 = tf.eye(2, 3, [1])
tensor_2 = tf.eye(3, 4, [2])
tensor_1.shape, tensor_2.shape

(TensorShape([1, 2, 3]), TensorShape([2, 3, 4]))

In [4]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.]]], dtype=float32)>

if tensor_1 shape is [x, y, z], tensor_2 shape should be [y, z, a]
where y and z match

In [5]:
tensor_3 = tf.ones([3, 2, 2])
tensor_3

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [6]:
# Change shape
tf.reshape(tensor_3, [4, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [38]:
tensor_4 = tf.random.Generator.from_seed(2).normal(shape=(2, 2, 4))
tensor_5 = tf.random.Generator.from_seed(2).uniform(shape=(1, 4, 5))

tf.matmul(tensor_4, tensor_5)

<tf.Tensor: shape=(2, 2, 5), dtype=float32, numpy=
array([[[ 1.5417138 ,  0.9519267 ,  1.1270944 ,  1.1228234 ,
          1.0628161 ],
        [-2.5476778 , -1.7859151 , -1.5100384 , -1.8356771 ,
         -1.096293  ]],

       [[-0.06013846,  0.45600736,  0.01394755, -0.6130394 ,
         -0.7100563 ],
        [ 2.9724422 ,  1.4066024 ,  1.0040293 ,  1.6954387 ,
          1.4357423 ]]], dtype=float32)>

`tf.matmul` can take `batch_size` where a tensor with shape (x, y, z) where x takes value of batch_size;
when multiplying matricies, `batch_size` has to be *same or 1*

In [45]:
tensor_6 = tf.constant([[2, 3, 5],
                        [4, 6, 8]])

tensor_6, tf.reshape(tensor_6, [3, 2]), tf.transpose(tensor_6)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 5],
        [4, 6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 4],
        [6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 6],
        [5, 8]], dtype=int32)>)

In [52]:
tensor_7 = tf.constant([[3, 1, 9],
                        [2, 4, 5]])

tf.tensordot(tensor_6, tensor_7, 0)

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 6,  2, 18],
         [ 4,  8, 10]],

        [[ 9,  3, 27],
         [ 6, 12, 15]],

        [[15,  5, 45],
         [10, 20, 25]]],


       [[[12,  4, 36],
         [ 8, 16, 20]],

        [[18,  6, 54],
         [12, 24, 30]],

        [[24,  8, 72],
         [16, 32, 40]]]], dtype=int32)>