In [1]:
import tensorflow as tf
import numpy as np

In [9]:
import numpy as np

# Change datatype (accuracy vs performance)
## tf.cast

In [4]:
tensor1 = tf.constant([3, 3, 3])
tensor1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3], dtype=int32)>

In [5]:
tensor2 = tf.cast(tensor1, dtype = tf.int16)
tensor2

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([3, 3, 3], dtype=int16)>

# Create tensor of set size with random values

## tf.constant(np.random.randint(min, max, size=x))

In [11]:
tensor4 = tf.constant(np.random.randint(-40, 40, size=50))
tensor4

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 24,  20,   9, -22, -30,  36,  -6,  12, -11,  35,  12,  21, -21,
       -14,  24,  16, -26,  20, -26, -35, -26, -39,  23, -37,   7, -30,
        -8,  -4,  11, -37, -19,  31, -25, -33,  25,   5,   9, -30,  -1,
        -5,  25,  12,   4,   6,   8,  -7, -32, -11,  -6,  39])>

# Aggregating tensors

1. absolute value
2. minimum
3. maximum
4. mean
5. sum

In [7]:
tensor3 = tf.constant(np.random.randint(-100, 100, size=10))
tensor3

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([-42,   9,  53,  70, -16, -58, -32,  58, -81,  10])>

In [8]:
# absolute value
tf.abs(tensor3)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([42,  9, 53, 70, 16, 58, 32, 58, 81, 10])>

In [9]:
# minimum
tf.reduce_min(tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=-81>

In [10]:
# maximum
tf.reduce_max(tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=70>

In [11]:
# mean
tf.reduce_mean(tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=-2>

In [12]:
# sum
tf.reduce_sum(tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=-29>

### VARIANCE AND STD HAVE TO BE IN FLOAT32

In [29]:
# variance
tensor3 = tf.cast(tensor3, dtype = tf.float32)
tf.math.reduce_variance(tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=2413.89>

In [30]:
# std
tf.math.reduce_std(tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=49.131355>