In [2]:
import tensorflow as tf
import numpy as np

In [3]:
#create scalar
scalar = tf.constant(7)
scalar

2022-07-31 02:18:39.451053: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
#create vector
vector = tf.constant([3, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
#create matrix
matrix = tf.constant([[3,7],
                      [7,3],
                      [4,2]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 7],
       [7, 3],
       [4, 2]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#create tensor
tensor = tf.constant([[[3, 7] , [7, 3]],
                     [[2, 4], [4, 2]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[3, 7],
        [7, 3]],

       [[2, 4],
        [4, 2]]], dtype=int32)>

In [10]:
tensor.ndim

3

In [11]:
variable_tensor = tf.Variable([2,7])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

In [20]:
variable_tensor[1].assign(20)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 2, 20], dtype=int32)>

shape = (row, column)

create tensors with tf.constant and tf.Variable

In [12]:
#generate random tensors
random = tf.random.Generator.from_seed(15).normal(shape=(3,2))
random

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.33149973, -0.5445254 ],
       [ 1.5222508 ,  0.59303206],
       [-0.63509274,  0.3703566 ]], dtype=float32)>

In [13]:
random2 = tf.random.Generator.from_seed(12).uniform(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.5751133 , 0.793342  ],
       [0.4289763 , 0.19118965],
       [0.7452506 , 0.41762006]], dtype=float32)>

In [14]:
tf.random.shuffle(random, seed=21)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.33149973, -0.5445254 ],
       [ 1.5222508 ,  0.59303206],
       [-0.63509274,  0.3703566 ]], dtype=float32)>

In [15]:
random3 = random
tf.random.set_seed(3)
tf.random.shuffle(random3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.5222508 ,  0.59303206],
       [-0.63509274,  0.3703566 ],
       [ 0.33149973, -0.5445254 ]], dtype=float32)>

tf.random.set_seed()

tf.random.shuffle

tf.random.Generator.from_seed().uniform(shape=(3,2))

In [16]:
#create tensor of all ones
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [17]:
#create tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

tf.ones

tf.zeros

tf.fill

Shape - # of elements in each dimension

Rank - number of dimensions

Axis/dimension - index of tensor (if you think of tensor as an array)

Size - number of elements

In [25]:
big_tensor = tf.eye(4, 6, [2, 2])
big_tensor

<tf.Tensor: shape=(2, 2, 4, 6), dtype=float32, numpy=
array([[[[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.]],

        [[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.]]],


       [[[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.]],

        [[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.]]]], dtype=float32)>

In [26]:
big_tensor[..., :-3]

<tf.Tensor: shape=(2, 2, 4, 3), dtype=float32, numpy=
array([[[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [0., 0., 0.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [0., 0., 0.]]],


       [[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [0., 0., 0.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [0., 0., 0.]]]], dtype=float32)>

In [29]:
big_tensor2 = big_tensor[..., tf.newaxis]
big_tensor2

<tf.Tensor: shape=(2, 2, 4, 6, 1), dtype=float32, numpy=
array([[[[[1.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [1.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [1.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [1.],
          [0.],
          [0.]]],


        [[[1.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [1.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [1.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [1.],
          [0.],
          [0.]]]],



       [[[[1.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [1.],
          [0.],
       

In [31]:
tf.expand_dims(big_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2, 4, 6), dtype=float32, numpy=
array([[[[[1., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0.]],

         [[1., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0.]]]],



       [[[[1., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0.]],

         [[1., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0.]]]]], dtype=float32)>

Append tensor

`x[:, :, tf.newaxis]`

`tf.expand_dims(tensor_name, axis=num)`

In [36]:
#Tensor basic operators /w tensorflow functions

tensor_1 = tf.constant([[[3, 2], 
                        [2, 2]],
                        
                        [[5, 8], 
                        [9, 5]]])
 
tf.multiply(tensor_1, 3)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 9,  6],
        [ 6,  6]],

       [[15, 24],
        [27, 15]]], dtype=int32)>